CREATE DATABASE BECAS
USE BECAS
CREATE TABLE ALUMNOS_BECARIOS (ID_BECARIO VARCHAR (5), NOMBRE VARCHAR (20), APELLLIDOS VARCHAR (35), PROMEDIO VARCHAR (5))
SELECT * FROM ALUMNOS_BECARIOS 
drop table ALUMNOS_BECARIOS
